### ISSUE TITLE
Turning off the Releases and Packages section

### ISSUE THREAD

**Issue by ghost** [Cyfrin/html-fund-me-f23#2]
I read it from one of the blogs, if we are not mentioning the Releases and Packages in the GitHub repo, it is a best practice to turn it off to make it look more professional.

## Image
![image](https://github.com/Cyfrin/html-fund-me-f23/assets/93525771/23d78072-500d-4d73-bd1c-f042764b3026)

**Comment by PatrickAlphaC** [comment]
Good call, thanks! Fixed for this one, I won't get around to the rest though. 

There are a _lot_ of these template dummy repos that I make. I'll see if I can remember to remove them moving forward. Thanks!
