### ISSUE TITLE
Lesson 8 QR code IPFS link  connect button not working on Brave browser

### ISSUE THREAD

**Issue by mooezz999** [Cyfrin/html-fund-me-f23#3]
Is it just me or does the IPFS link connect wallet button not working on my brave browser?

**Comment by mooezz999** [comment]
I found the challenge addresses in the page source

**Comment by foufrix** [comment]
Had exactly the same issue, I think it's part of the problem to solve to dig into js file and find the clue in it

**Comment by Kel-VinTech** [comment]
anyone figured out how to do this?

**Comment by Shane0xM** [comment]
Having a similar issue. When I attempt to "fund", I receive the below error message:

![Internal JSON-RPC error](https://github.com/Cyfrin/html-fund-me-f23/assets/169729951/1ef33577-650c-44c0-ab5b-6f11359e20ed)

I have troubleshooted the Anvil network a few times and ensured the balance on the connected wallet is enough to cover gas + fees in the imported account on Anvil.

**Comment by Shane0xM** [comment]
This is the error in the console:

The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.

**Comment by PatrickAlphaC** [comment]
Usually from what I've seen, is that this is an error with your RPC provider. Sometimes I get this issue with Alchemy, and when I try a different RPC provider it works.

**Comment by Shane0xM** [comment]
Thanks for response. I'll keep this in mind and give it a try.
