### ISSUE TITLE
Getting error when click on the Fund button.

### ISSUE THREAD

**Issue by Akash-Kolekar** [Cyfrin/html-fund-me-f23#8]
### Frontend Error when click on the `Fund` button

**I'm getting `an error `when I try to `fund` the `FundMe` contract using `frontend` but when I fund with `script` it is running fine. 
**`Other buttons are working fine`**, there might be an `issue` with the Fund button, or am making a mistake somewhere.** 

# Here is the image of the error:
![image](https://github.com/user-attachments/assets/7237db55-7643-45ee-9e26-4348402c96b5)

**I have tried with `Anvil, Zksync and Sepolia` the result is the same getting issue when trying to fund using the frontend.**

**Comment by PatrickAlphaC** [comment]
whoops! I had the wrong ABI here. Fixed it, thank you!

5a9450348fa4a2acb74a8621a5eef3ede2c3186c
